### ISSUE TITLE
Waypoint not rendering custom child node

### ISSUE THREAD

**Issue by ThekhoN** [dzhurley/preact-waypoint#2]
Hi i've been using https://github.com/dzhurley/preact-waypoint  - minimal preact version of https://github.com/brigade/react-waypoint
i just noticed that,
preact-waypoint "fails" to render the child component inside <Waypoint/>
it always renders 
```
<Waypoint><span></span></Waypoint>
```
 even if i put  
```
<Waypoint><div className='myContent'>content</div></Waypoint>
```
react-waypoint is effectively able to query the viewport by reading the 
```
<Waypoint><div className='myContent'>content</div></Waypoint>
```
and thus handle the onEnter & onLeave events

**Comment by dzhurley** [comment]
Hi @ThekhoN, thanks for the PR!

I hadn't actually considered the child component case for my port, I had just been using it as an invisible marker to help with infiniscroll loading in Preact. I've updated `preact-waypoint` to render children if they exist, if you bump to 1.0.7 it should be fixed.
